### ISSUE TITLE
Mine Type on Voss is not correct

### ISSUE THREAD

**Issue by AndreaNicola** [joeycrash135/stfc-galaxy-map#11]
Hi, 

The mines on Voss are only 3* Raw Gas mines.

**Comment by joeycrash135** [comment]
Correct mine data will come soon, I just finished up my add command on the discord bot. I'll open up invites to the bot soon. This way I can harvest the information a lot faster.

**Comment by joeycrash135** [comment]
corrected voss, added all the latinum systems too
