### ISSUE TITLE
Amador have 2* Gas not 3*

### ISSUE THREAD

**Issue by bobbelsche** [joeycrash135/stfc-galaxy-map#2]
nice job so far :)

System: Amador [19]
ID: 959318428
Faction: Independent
Hostiles: Sona Pirate, Suliban Nomad
Hostiles Range: 18-20
Ship Types: Battleship, Interceptor
Warp Range:
-> Mines: 3* Raw Crystal, Dilithium
Station Hubs:
Linked Systems: Labac, Ione, Araiza, H'ganrem, Rakkaus, Ocus, Laidcenn, Fastolf

**Comment by joeycrash135** [comment]
Hello bobbelsche! Thanks for your feedback. There is quite a bit of data to sort out and confirm valid. I have built a discord bot to go along with the website.
 I am finishing up !add & !update commands so the community can help catalog the data.
If you are interested, private message me your discord username and I'll invite you to my testbed.

**Comment by joeycrash135** [comment]
Amador now shows 2* crystal and dilithium. More system data to follow.
