### ISSUE TITLE
Nice work!

### ISSUE THREAD

**Issue by AndreaFaso** [joeycrash135/stfc-galaxy-map#3]
First of all, let me say it's a very good job. Well done!
Your code is good and I'd like to help doing some improvement.
During the next weekend, I will set up a website for my alliance and I was searching for maps on the web. Yours seems to be the best one.
If you are interested I will share my ideas and my code with you and also I'd like to help you testing you discord's bot and, eventually, bringing there also some mates to help to update and improve data from the game.

**Comment by joeycrash135** [comment]
Thank you for your interest! I'd like to hear your opinions and ideas. I would definitely appreciate having some more data contributors.

**Comment by joeycrash135** [comment]
https://discord.gg/ZZdWNE  <--join asap, please just you. I will boot any unexpected guests. I'm not ready to open the doors yet.
