### ISSUE TITLE
Additional Map Info

### ISSUE THREAD

**Issue by Colton-Bell** [joeycrash135/stfc-galaxy-map#6]
Great job, love this map, but is there anyway you could add the number of planets / base locations per system?

**Comment by joeycrash135** [comment]
Hi, thanks for the feedback. That's in the works and will be available as
soon as I can find time to continue working on it

**Comment by joeycrash135** [comment]
I am in the process of data collection for every node in the galaxy. I will add this when I get enough data. I'll be able to determine exactly how many of any node in system or the full viewable galaxy.
