### ISSUE TITLE
Add Infos (some suggestions)

### ISSUE THREAD

**Issue by AndreaFaso** [joeycrash135/stfc-galaxy-map#8]
On my local map I've added loot as system data (not referred to ships...not needed from my point of view).
I've also developed three different map view:
1 - Mining resources
2 - Enemy Ships type
3 - Hostiles Loot

Actually to speed up map online usage (I've only a little time to develop map...) I've added a "Trick" system (not visible on the map) to add on the first line all Resouces, Ship Types and Loots in the desired order to have them correctly ordered in the select panel.

If you are interested I can share here my code to show how I've done these changes.

**Comment by joeycrash135** [comment]
Let me think about this. I'd like to keep this base map somewhat simple for easy adoption by other developers. Maybe I can setup a config file with properties that can be toggled on/off. I'll leave this open for now.

**Comment by joeycrash135** [comment]
I'm going to pass on this for now, I will have the discord bot handle custom views.
The loot is still very random. I will reconsider down the road.
